### ISSUE TITLE
Update the style guide with to improve topic segmentation and branching

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/docs-template#14] opened 2023-11-19 22:01 UTC
See: https://docs.google.com/document/d/1LU-szHDxPqmwqu_mYhr3fCE0f2cSWhPhDMELuWiyu_I/edit

**Comment by alexandratran** [comment] 2024-08-15 19:15
Duplicate of #18

**Closed by alexandratran** 2024-08-15 19:15 UTC
